---
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    cert-manager.io/cluster-issuer: "letsencrypt"
  hosts:
    - host: it-elk.ls.lsst.org
      paths:
        - path: /
  tls:
    - secretName: elk-tls
      hosts:
       - it-elk.ls.lsst.org
