---
# Source: elasticsearch/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  labels:
    heritage: "Helm"
    release: "elasticsearch"
    chart: "elasticsearch"
    app: "elasticsearch"
  annotations:
    {}
spec:
  type: LoadBalancer
  selector:
    release: "elasticsearch"
    chart: "elasticsearch"
    app: "elasticsearch"
  ports:
  - name: http
    protocol: TCP
    port: 9200
  - name: transport
    protocol: TCP
    port: 9300
