---
# Source: logstash/templates/configmap-pipeline.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-logstash-pipeline
  labels:
    app: "logstash-logstash"
    chart: "logstash"
    heritage: "Helm"
    release: "logstash"
data:
  logstash.conf: |
    input {
      syslog {
        port => 5144
        syslog_field => "syslog"
      }
    }
    output {
      stdout {
        codec => rubydebug
      }
    }