input: |-
  udp {
    port => 1514
    type => syslog
  }
  tcp {
    port => 1514
    type => syslog
  }
  http { port => 8080 }

containerPorts:
  - name: syslog-udp
    containerPort: 1514
    protocol: UDP
  - name: syslog-tcp
    containerPort: 1514
    protocol: TCP
  - name: http
    containerPort: 8080
    protocol: TCP
  - name: monitoring
    containerPort: 9600
    protocol: TCP

service:
  type: LoadBalancer
  ports:
    syslog-udp:
      port: 1514
      targetPort: syslog-udp
      protocol: UDP
    syslog-tcp:
      port: 1514
      targetPort: syslog-tcp
      protocol: TCP
  loadBalancerIP: "139.229.135.153"
